[build]
environment = {YARN_FLAGS = "--offline --ignore-optional", NODE_VERSION = "14.16.1"}

[[redirects]]
  from = "/fr"
  to = "/?lang=fr"
  status = 301
  force = true

[[redirects]]
  from = "/fr/accessibility"
  to = "/accessibility/?lang=fr"
  status = 301
  force = true

[[redirects]]
  from = "/fr/capabilities"
  to = "/capabilities/?lang=fr"
  status = 301
  force = true
